version: '3'

services:
  coco-dev:
    image: jamieleecho/coco-tools:0.3
    environment:
      - HOME=/home/$USER
    volumes:
      - $HOME/..:/home

  run-tests:
    image: jamieleecho/coco-tools:0.3
    volumes:
      - ./:/coco
    working_dir: /coco
