version: '3'

services:
  test:
    build: .
    command: bash -c "
        pycodestyle src tests setup.py &&
        pytest --cov=src"

  testv:
    build: .
    command: bash -c "
        pycodestyle src tests setup.py &&
        pytest --cov=src"
    volumes:
    -  .:/root/coco-tools

  bash:
    build: .
    command: bash

  bashv:
    build: .
    command: bash
    volumes:
    -  .:/root/coco-tools

